appium/appium-desktop

app/actions/StartServer.js, app/components/StartServer/AdvancedTab.js, app/components/StartServer/DeletePresetButton.js, app/components/StartServer/PresetsTab.js, app/components/StartServer/StartButton.js, app/components/StartServer/shared.js, app/reducers/StartServer.js, appium.js, package.js, server.js, webpack.config.development.js
=> allow deleting of presets

app/actions/ServerMonitor.js, app/actions/StartServer.js, app/components/ServerMonitor.css, app/components/ServerMonitor.js, app/reducers/ServerMonitor.js
since we get logs from Appium before it has a chance to
review please @dpgraham
=> display timestamps if logTimestamps is set

app/actions/Inspector.js, app/actions/Session.js, app/components/Inspector.css, app/components/Inspector/HighlighterRect.js, app/components/Inspector/Screenshot.js, app/components/Inspector/shared.js, appium.js, package.json
-Encapsulated method calls on the main process in the form of a promise (the method call sends a UUID to the main process along with the methodName and args; a promise is stored with the UUID as it's key; when the method call is complete the main process reports the result back along withe the UUID; the promise is then resolved)
-Added a coordinate parser which handles determining the bounds of an iOS or Android element
-Calculates the image scaling ratio based on the width of the top element vs the calculated with of the image
=> Further revisions to inspector

README.md, app/actions/Inspector.js, app/actions/Session.js, app/components/Inspector/SelectedElement.js, app/components/Session.css, app/components/Session.js, app/components/Session/NewSessionForm.js, package.json
-Added 'electron-rebuild' to fix problem with SQLite3 native module not working with electron
-Some CSS fixes
-Better handle dcaps type changes
Reviewer: @jlipps
=> SQLite3 and CSS problems fixed

app/actions/Inspector.js, app/components/Inspector.css, app/components/Inspector.js, app/components/Inspector/SelectedElement.js, app/components/Inspector/Source.js, app/reducers/Inspector.js, appium.js
-Increased browser window width from 1200 to 1500
-Moved inspector into a third pane.
-Changed sendKeys so that pushing the button opens a modal where you specify the keys
=> Made layout 3 panes and made sendKeys a modal

app/app.global.css, app/components/ServerMonitor.css, app/components/ServerMonitor.js, app/components/StartServer/AdvancedTab.css, app/components/StartServer/AdvancedTab.js, app/components/StartServer/DeletePresetButton.js, app/components/StartServer/PresetsTab.css, app/components/StartServer/PresetsTab.js, app/components/StartServer/SavePresetButton.js, app/components/StartServer/SimpleTab.css, app/components/StartServer/SimpleTab.js, app/components/StartServer/StartButton.js, app/components/StartServer/StartServer.css, app/components/StartServer/StartServer.js, app/containers/App.js, package.json
=> rewrite server start and monitor components with antd, remove react-photonkit

app/actions/Inspector.js, app/actions/Session.js, app/app.global.css, app/components/Inspector.css, app/components/Inspector.js, app/components/Inspector/HighlighterRect.js, app/components/Inspector/Screenshot.js, app/components/Inspector/SelectedElement.js, app/components/Inspector/Source.js, app/components/ServerMonitor.css, app/components/ServerMonitor.js, app/components/Session.css, app/components/Session.js, app/components/Session/FormattedCaps.js, app/components/Session/NewSessionForm.js, app/components/Session/SavedSessions.js, app/components/StartServer/AdvancedTab.css, app/components/StartServer/AdvancedTab.js, app/components/StartServer/StartServer.css, app/reducers/Inspector.js, app/reducers/Session.js, appium.js, package.json
@dpgraham can you go ahead and take a look? this is all for the new session creation window. i'll be working on the inspector window and pushing it in a follow-up commit to this PR. lot of crazy CSS stuff in here that's probably easiest to evaluate by checking out the branch and building.
=> revamp UI of new session creation window

app/main/appium.js, app/main/main.development.js, app/renderer/components/Session.css, app/renderer/components/Session.js, webpack.config.base.js
=> more windows and misc fixes

app/main/appium.js, app/main/menus.js, app/renderer/actions/Session.js, app/renderer/actions/StartServer.js, app/renderer/components/Session.js, app/renderer/reducers/Session.js
=> enable launching of new session window even when server isn't running

app/renderer/actions/Session.js, app/renderer/components/Session.js, app/renderer/reducers/Session.js
=> add testobject server type and api key handling

app/main/appium.js, app/main/auto-updater.js, app/main/main.development.js, app/main/menus.js, app/main/mock-updater.js, app/renderer/actions/Session.js, app/renderer/actions/Updater.js, app/renderer/components/Updater.css, app/renderer/components/Updater.js, app/renderer/components/Updater/CheckForUpdates.js, app/renderer/components/Updater/DownloadUpdate.js, app/renderer/components/Updater/FoundUpdate.js, app/renderer/components/Updater/UpdateError.js, app/renderer/containers/UpdaterPage.js, app/renderer/reducers/Updater.js, app/renderer/reducers/index.js, app/renderer/routes.js, package.json
* Simplified the logic for the autoUpdater. AutoUpdater on main process manages it's own state and then synchronizes the state with the BrowserWindow
* Added CSS styling
=> Auto updater finishing touches

app/renderer/actions/Session.js, app/renderer/actions/StartServer.js, app/renderer/reducers/index.js
=> set defaults for all settings in one place (fix #52)

CHANGELOG.md, app/main/appium.js, app/renderer/actions/Session.js, app/renderer/actions/StartServer.js, app/renderer/reducers/StartServer.js, app/renderer/reducers/index.js, app/settings.js, package.json
there was some issue with settings.defaults not working the way i expected. i put it in its own file and now we're just using the same settings object across the board so it should be safer.
review please @dpgraham.
=> fix issue with typing into desired caps box

app/main/appium.js
so keystrokes work in sims (fix #61)
=> ensure connectHardwareKeyboard is on by default 

appveyor.yml
So that AppVeyor can publish windows exe
=> Add GH_TOKEN to appveyor.yml

app/renderer/components/Updater/DownloadUpdate.js, app/renderer/components/Updater/FoundUpdate.js
* Was setting value on textArea without calling onChange; uses 'defaultValue' instead
* Removed nested 'p' tag; uses span instead
=> Fixed bad markup in Update component

app/main/auto-updater.js, app/main/menus.js, app/main/mock-updater.js, app/renderer/components/Updater/CheckForUpdates.js, app/renderer/components/Updater/DownloadUpdate.js
* Round download progress and use mb instead of b
* Disable autoDownload
* Add 'About Appium' and 'Check for Updates' menu	
* Add check for updates menu in Windows
=> Windows updater fixes

app/main/auto-updater.js, app/renderer/components/Updater/CheckForUpdates.js, app/renderer/components/Updater/DownloadUpdate.js, app/renderer/components/Updater/FoundUpdate.js, app/renderer/components/Updater/Updater.css
* On first run on windows wait 20s before update
* Show link for platforms not supporting auto update
* Ask user to close Appium instead of restarting it
=> squirrel.windows 'first run' fix; fixed wording in auto updater

app/renderer/components/ServerMonitor/ServerMonitor.js, app/renderer/reducers/ServerMonitor.js
=> ensure timestamps are properties of log lines, not the log window

.travis.yml
* Increase Travis timeout to 30 minutes
=> Increase timeout of package-ci to 30 minutes

app/renderer/components/Session/NewSessionForm.js
...and use that as the filepath
=> getLocalFilePath returns arrays, get first value

app/renderer/actions/Session.js
Switch from http port 80 to https port 443
=> Fix openSSL problem on test object

app/renderer/actions/Inspector.js, app/renderer/actions/shared.js
* Some functions in Inspector.js may need to be re-used so moved it to a shared actions file
=> Moved functions from inspector to shared

app/renderer/components/Session/Session.js
=> Add link to desired capabilities documentation

app/renderer/actions/Inspector.js, app/renderer/util.js, package.json, test/unit/util-specs.js
* Added unit tests to project
* Wrote helper method that takes a DOMNode and an array of unique attributes and returns an optimal xpath of the form `//tagname[@<id>=<id-value]/other-tag[<index>]/other-tag[<index>]`
* Changed the component so that it uses the xpath optimizer instead of just crawling through indices
(reviewers @jlipps)
=> Optimize xpath

app/renderer/actions/Session.js, app/renderer/components/Session/Session.js
* If no sauce username or key provided, use what's in env variables
* If no TestObject host provided or TestObject key use what's in env variables
(reviewer: @jlipps)
=> Use env variables for SauceLabs and TO

app/renderer/app.global.css, app/renderer/components/Session/AttachToSession.js
=> Move refresh button inside <Select>; add placeholder

package.json
tested locally and it works great.
=> update appium to 1.6.5

app/renderer/components/Inspector/Inspector.css, app/renderer/components/Inspector/Inspector.js
* When scroll buttons show, the bottom is unclickable
* Added padding so that we can scroll to it
* Fixed incorrectly placed ID's too
=> Added padding to bottom of source tree

app/renderer/actions/Inspector.js, app/renderer/actions/shared.js, app/renderer/components/Inspector/ElementLocator.js, app/renderer/components/Inspector/Inspector.css, app/renderer/components/Inspector/Inspector.js, app/renderer/components/Inspector/LocatedElements.js, app/renderer/components/Inspector/LocatorTestModal.js, app/renderer/components/Inspector/Source.js, app/renderer/lib/client-frameworks/framework.js, app/renderer/lib/client-frameworks/java.js, app/renderer/lib/client-frameworks/js-wd.js, app/renderer/lib/client-frameworks/js-wdio.js, app/renderer/lib/client-frameworks/python.js, app/renderer/lib/client-frameworks/ruby.js, app/renderer/reducers/Inspector.js
* Added icon to the top bar that opens the modal
* Can select a locator strategy from a hard-coded select dropdown
* Can enter a locator value in an input text
* Shows the results in the same modal, inside a multi-select (only shows the ID's)
* Added a button that clicks on the selected element
=> Added locator tester modal

test/integration/appium-method-handler.integration-test.js
* Last commit that updated the recorder broke tests
=> Fix broken tests

app/renderer/actions/Session.js, app/renderer/components/Session/Session.css, app/renderer/components/Session/Session.js, app/renderer/reducers/Session.js, app/renderer/styles/app.global.css
* Add a checkbox in the custom server panel that allows you to use https
* Add a dropdown that lets you select the TestObject data center
(note this PR is ahead of the tip of another PR)
=> UI updates requested by TestObject

CHANGELOG.md, package.json
(this is a v1.2 branch so don't delete the branch after rebasing)
=> Prepare for v1.2.0-beta.1

app/renderer/actions/Session.js, app/renderer/components/ServerMonitor/ServerMonitor.css, app/renderer/components/ServerMonitor/ServerMonitor.js, app/renderer/components/Session/Session.js, package-lock.json
enables sending all http commands via sc proxy (helpful when users can't hit ondemand.saucelabs.com directly from their work machines due to firewall restrictions, but sc proxy has been approved already).
also fixed up some visual design of the server monitor that was bugging me.
=> add sauce connect proxy option to sauce server config

app/renderer/components/Inspector/Source.js
Make sure error can be printed. See https://github.com/appium/appium/issues/8856
=> Fix error reporting for source error

app/renderer/actions/Inspector.js, app/renderer/components/Inspector/SelectedElement.js, app/renderer/reducers/Inspector.js
* Notification was kind of vague
* Replaced it with alert on the right panel that tells the user when they can't do the basic interactions with an element
=> Remove element not found notification

app/main/appium.js, app/renderer/actions/Session.js, app/renderer/components/Inspector/RecordedActions.js, app/renderer/components/Session/Session.css, app/renderer/components/Session/Session.js, app/renderer/lib/client-frameworks/framework.js, app/renderer/lib/client-frameworks/java.js, app/renderer/lib/client-frameworks/js-wd.js, app/renderer/lib/client-frameworks/js-wdio.js, app/renderer/lib/client-frameworks/python.js, app/renderer/lib/client-frameworks/ruby.js
- enable /custom/server/path
- ensure ssl box looks checked when the data is on
- ensure urls in recorder boilerplate are generated correctly
=> fix up custom server tab

app/renderer/actions/ServerMonitor.js, app/renderer/components/ServerMonitor/ServerMonitor.js
=> keyboard shortcut to clear terminal logs

CHANGELOG.md, package.json
* Also added missing changelog for v1.3.2
* I'll make a PR after that includes Appium v1.8 beta once we get shrinkwrap stuff sorted out and I do some basic testing with it
=> Prepare for v1.4.0

app/renderer/components/Session/ServerTabCustom.js, app/renderer/components/Session/ServerTabTestobject.js
These are already in the `Advanced Setting` collapsible
=> Remove unneeded unauthorized SSL fields

app/main/appium-method-handler.js, app/main/appium.js, app/renderer/actions/Inspector.js, app/renderer/components/Inspector/Screenshot.js
If user kills a session, don't show the notification error
=> Don't show quit error if quit initiated by user

app/main/appium-method-handler.js, app/main/appium.js
* Don't run loop for local sessions
* Change time limits
=> Fixes for keepAlive

.travis.yml, package-lock.json, package.json
Followed Travis configuration instructions: https://github.com/greenkeeperio/greenkeeper-lockfile
=> Greenkeeper locks

app/renderer/lib/client-frameworks/index.js, app/renderer/lib/client-frameworks/robot.js
* Add the RobotFramework option to allow exporting the recorded session to a runable RobotFramework syntax, usign the variables and capabilities needed and obtained from caps
=> Add RobotFramework export option on the recorder

app/renderer/lib/client-frameworks/robot.js
Error on bad merging and forgot to add this change.
This change is not application blocking, but the exported result for RobotFramework testing, will have 2 syntax errors
=> Fix error on variable generation and params

app/renderer/actions/ServerMonitor.js, app/renderer/actions/Session.js, app/renderer/actions/StartServer.js, app/renderer/components/Config/Config.js
* Some listeners are being bound multiple times which is causing the same function to be called multiple times
* Unbind all listeners when we're done with them
=> Unbind ipc renderer listeners

.travis.yml, app/main/appium-method-handler.js, app/main/appium.js, package-lock.json
* Move method handlers into appium-method-handler as static methods
* Make it killSession synchronous because there was a race condition where sessions were being killed as new one was being created and caused a crash
* This method can be synchronous because we don't use the result and it's fine to 'fire-and-forget'. There's nothing that needs to be waited for
=> Make killSession synchronous

app/empty-module.js, app/renderer/actions/ServerMonitor.js, package-lock.json, package.json, webpack.config.base.js
Greenkeeper/appium support 2.22.0
=> Fix missing module webpack problem

.mocharc.js, package-lock.json, package.json, test/e2e/.mocharc.js, test/mocha.opts
=> chore: Upgrade to mocha 6

app/main/sentry-permission-prompt.js
closes https://github.com/appium/appium/issues/12254
=> fix typo in prompt

ci-jobs/crowdin.yml
This pipeline runs `npm run crowdin-update` on every commit to master
=> chore: Fix ENV secret problem

ci-jobs/ci.yml
Just a basic CI build to run on Azure that builds the project and runs the unit/integration tests. This will run on every commit to every branch.
=> Add basic ci build

app/renderer/components/Inspector/ElementLocator.js, app/renderer/lib/client-frameworks/java.js, app/renderer/lib/client-frameworks/js-wd.js, app/renderer/lib/client-frameworks/js-wdio.js, app/renderer/lib/client-frameworks/python.js, app/renderer/lib/client-frameworks/robot.js, app/renderer/lib/client-frameworks/ruby.js
* Add data matcher as search strategy
* Added client recording code ahead of https://github.com/appium/appium/issues/12372
=> feat: Add DataMatcher search strategy

app/renderer/components/Inspector/HighlighterRect.js, app/renderer/components/Inspector/Screenshot.js, package-lock.json
Reverts appium/appium-desktop#813
@muyoungko I'm going to have revert this, sadly. I was testing it today and I had some cases where I was mousing over menu items and it was selecting the entire app Window.
=> Revert "Add way to select overlapped behind views of Screenshot component"

app/main/menus.js
Fix for raw (without localization) "Learn more" into the main menu
=> Fix "Learn More" without localization in menu

app/renderer/actions/Session.js, app/renderer/components/Session/ServerTabSauce.js, app/renderer/reducers/Session.js, assets/locales/en/translation.json
(Started by @vrunoa)
Cleaned up reducer logic too.... added default states for the cloud providers in the INITIAL_STATE object.
=> Add sauce datacenters

app/renderer/components/Session/FormattedCaps.js, app/renderer/components/Session/SavedSessions.js, app/renderer/components/Session/Session.css
this has been bugging me for a long time. finally got things working the way i want.
=> make sure formatted caps stays visible in saved caps area

app/renderer/actions/Session.js, app/renderer/components/Session/ServerTabHeadspin.js, assets/locales/en/translation.json
The local desctiption might tweak more.
=> tweak headspin panel

app/renderer/components/Session/FormattedCaps.js, package-lock.json, package.json
Use 'ClickOutside' component that saves capabilities when clicking outside component.
=> feat: Save capabilities when click outside component

app/configs/app.config.js, assets/locales/en/translation.json
https://crowdin.com/project/appium-desktop/pt-BR#
(after merging, will run `npm run crowdin-update` to update the crowdin project)
=> docs: add pt-bz translation

app/main/appium-method-handler.js
Fix swipe command by adding a 500ms wait between press and moveTo
=> feat: Fix Swipe by Coordinates #4268

package-lock.json
=> fix: update safer-eval

app/renderer/lib/client-frameworks/index.js, app/renderer/lib/client-frameworks/js-oxygen.js
@dpgraham, as per our previous discussion - this pull request adds Oxygen framework support.
=> feat: Add OxygenHQ framework support in Inspector Recorder.

app/renderer/components/Inspector/ElementLocator.js, app/renderer/components/Session/SavedSessions.js, package-lock.json, package.json
- Update to the latest electron
- I could not find any warning message for it
- Fix warning messages
- Update `antd`
- Use `onRow` instead of `onRowClick` following a warning message
- Tested on SavedSessions tab to save/edit preferences on the tab
- Remove unused line
I also conducted some scenarios, create session/open several buttons etc. They worked without warnings/critical error messages.
=> feat: Update to electron 7

app/renderer/lib/client-frameworks/java.js, app/renderer/lib/client-frameworks/js-wd.js, app/renderer/lib/client-frameworks/js-wdio.js, app/renderer/lib/client-frameworks/python.js, app/renderer/lib/client-frameworks/robot.js, app/renderer/lib/client-frameworks/ruby.js
Record feature for https://github.com/appium/appium-desktop/pull/1231
=> feat: Add record for Web/Context commands

app/renderer/components/Inspector/Actions.js, app/renderer/components/Inspector/Inspector.js, app/renderer/components/Inspector/RecordedActions.js, app/renderer/components/ServerMonitor/ServerMonitor.js, app/renderer/components/Session/CapabilityControl.js, app/renderer/components/Session/Session.js, app/renderer/components/StartServer/StartButton.js
- `LegacyIcon` in https://github.com/appium/appium-desktop/pull/1259
- A layout fix in `Actions.js`
=> feat: Update to antd v4 - 2

app/renderer/components/Session/SavedSessions.js
https://ant.design/components/table/#Migrate-to-v4
I found a warning message about `onRowClick`
=> fix: use onClick for antdv4

app/renderer/actions/Inspector.js, app/renderer/util.js, test/unit/util-specs.js
https://github.com/appium/appium-desktop/issues/1346
=> fix: Make sure xml parsing does not corrupt Unicode characters

package-lock.json, package.json
Another trial of https://github.com/appium/appium-desktop/pull/1380
Perhaps we should fix some issues in Antd 4.1+
=> fix: build error

ci-jobs/weekly.yml
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9725&view=logs&j=3fb81b97-cac2-575f-7880-79069b8b5203
=> ci: bump macOS version to 10.15 for weekly

app/renderer/components/StartServer/AdvancedTab.js, assets/locales/en/translation.json
=> feat: add Allow CORS in advanced tab

app/renderer/components/Inspector/SelectedElement.js
https://github.com/appium/appium-desktop/issues/1483
=> fix: undefined length in SelectedElement

.github/workflows/weekly.js.yml
I'll create another PR to remove the previous weekly.yml and rename this file name.
Created PR by this change: https://github.com/appium/appium-desktop/pull/1488
=> ci: Update weekly.yml

.github/workflows/translation.yml
=> ci: Update translation.yml

ci-jobs/package.yml, ci-jobs/pr-validation.yml
Windows host is very unstable.
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=10616&view=results
Let me follow the latest format and run the packaging script with it.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
=> ci: follows new param

package-lock.json, package.json
https://github.com/appium/appium-desktop/issues/1507#issuecomment-671221606
We should bundle mjpeg-consumer into this electron package
=> feat: add jpeg consumer

package-lock.json, package.json
=> chore: bump the version to 1.18.0-2

package-lock.json, package.json
Bump embedded appium version to 1.18.2
=> feat: bump appium version to 1.18.2

package-lock.json, package.json
- Bump appium version
- https://github.com/appium/appium-desktop/pull/1584
To be able to release appium-desktop with appium@beta (for 1.19.0)
=> feat: bump appium version and AD version

app/main.js, app/override/index.js, app/override/override_http.js, app/override/override_https.js
=> feat: override NodeJS' request method of the http(s) modules for adding a User-Agent header

inspector/app/renderer/components/Session/AttachToSession.js, inspector/app/renderer/reducers/Session.js
https://github.com/appium/appium-desktop/pull/1727 to current master
=> fix: stale session ids being displayed in the attach to session dropdown (to master)

inspector/app/renderer/components/Session/AttachToSession.js
https://github.com/appium/appium-desktop/pull/1694/files to master
=> feat: add sessionName in the attach to session dropdown

app/override/override_http.js, app/override/override_https.js
To keep backward compatibility
=> chore: tweak UA for compatibility

app/override/override_http.js, app/override/override_https.js
https://github.com/appium/appium-desktop/issues/1708#issuecomment-816149339
For current master and https://github.com/appium/appium-inspector
=> chore: Use appium-inspector as UA

.github/workflows/translation.yml
https://github.com/appium/appium-desktop/actions/runs/1018954228 The error was from an action
=> ci: update create-pull-request

package-lock.json, package.json
=> chore: bump to v9

assets/locales/en/translation.json
Updating localized strings in translation.json for the element selection feature in Appium Inspector.
=> update: add strings to translation.json

CONTRIBUTING.md, app/renderer/components/ServerMonitor/ServerMonitor.js
I have always wanted this feature in order to look at more logs at once.
Also, it looks like the CONTRIBUTING.md was not updated since the split of `server` and `inspector`.
Thanks all!
=> Update CONTRIBUTING.md and add ability to decrease and increase font size of console

app/renderer/components/ServerMonitor/ServerMonitor.js, package-lock.json, package.json
* Fixed logLevel not being honored
* Fixed icons to distinguish log level
* Removed `silly` in leveler
=> Fix for logLevel being honored and icons for log levels cleanup to accept colorized logs from Appium

assets/locales/en/translation.json
https://github.com/appium/appium-inspector/pull/591/files#diff-045d5895e12e7919980482ddc05bd9ccd330c3dc7e8adcf9bd146734032d78a0R14
=> feat: add it
