- webpack.config.electron.js
- webpack.config.production.js
-Removed Uglifying of NodeJS code because it currently is incompatible with ESHarmony
-Point Node NPM packages entry points to 'main' (webpack does 'browser' by default). Pointing packages to 'browser' caused the code to break because of Reference Errors (window is not defined)
-Added 'babel-polyfill' to renderer webpack entry points
> Fixed npm start errors

- app/components/Inspector/Source.js
If an empty array is passed into a treenode it still shows the expander arrow. Instead of passing an empty array it passes null.
> Set TreeNode children to null if no children

- app/main/main.development.js
- package.json
- webpack.config.electron.js
> use shell-env to ensure we get env vars when running the app (fix #45)

- app/main/auto-updater.js
- app/main/mock-updater.js
- app/renderer/components/Updater/DownloadUpdate.js
* The autoUpdater has a `download-progress`. Previously we were waiting for that event to be emitted before we show the download indicator, but it turns out that in practice the download starts before the first `download-progress` event is ever emitted, so this fix shows the indicator right away
> Add logging to autoUpdater and fixed functionality

- app/main/mock-updater.js
- app/renderer/components/Updater/FoundUpdate.js
- app/renderer/components/Updater/Updater.css
* Was using percentage previously and header was getting clipped
* Now it sets the container to column flex with  height 100% of viewport
* The header and footer don't have flex-grow set
* The body (which contains the 'release notes' textarea) has flex-grow=1 which causes it to take up all the remaining space
* The body is also given a 'flex' display type which causes it's children to take up all the space (height 100% on textarea doesn't work)
> Use flex to align items in FoundUpdate component

- app/main/auto-updater.js
- app/renderer/components/Updater/FoundUpdate.js
- app/renderer/components/Updater/Updater.css
- package.json
* Get version from package.json
* Call endpoint to get release notes for that version (https://api.github.com/repos/appium/appium-desktop/releases/tags/v${version}) from auto-updater.js
* Also added padding to textarea (it looked weird with no padding)
> Get release notes from GitHub API

- app/main/appium.js
Attached sessions get terminated when closing the inspector, which is quite annoying in my opinion. The initiator of the session should be responsible for deleting it.
> Do not quit attached session when closing the inspector

- app/renderer/app.global.css
For some reason antd has a max height on the ant-spin of 320 px which was causing the spinner to not be centered
> Remove max-height on .ant-spin

- app/renderer/app.global.css
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/SourceScrollButtons.js
* Added component that has a left and right scroll button that takes a container as an argument
* Clicking left makes the scrollLeft -= 20, click right makes the scrollLeft += 20
* Doesn't show component if clientWidth > scrollWidth
(reviewer @jlipps)
> Add buttons that scroll source left and right

- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/util.js
- package.json
- test/unit/util-specs.js
* Added try-catch so that if XPath.select throws an exception within the for loop, it just continues the loop and skips past the attribute that it's testing
* Added another try-catch within the entire method so that if there is some other unexpeccted exception, it returns null and we don't show xpath on the selected elements pane (this case is unlikely given that XPath.select is the only method that we would expect to throw an exception)
* Added regression tests that reproduce the above exceptions and confirmed the fix
(reviewer @jlipps)
> Fix for xpath parse exception

- test/e2e/main-e2e.test.js
* Travis already has the e2e timeout set to 10 minutes
* Increase AppVeyor to 10 minutes too (AppVeyor was sometimes timing out and this was breaking build)
(reviewer @jlipps)
> Increase e2e test timeout on AppVeyor

- README.md
- app/main/appium.js
- app/renderer/actions/Session.js
- app/renderer/components/Session/AttachToSession.js
- app/renderer/components/Session/Session.js
- app/renderer/reducers/Session.js
* Instead of having to hardcode session id's, the desktop app gets the list of sessions from /wd/hub/sessions endpoint
(reviewer @jlipps)
> Gets list of running sessions from Appium

- app/main/appium.js
- app/renderer/actions/Inspector.js
- app/renderer/actions/shared.js
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/Source.js
- app/renderer/reducers/Inspector.js
* Added more try-catch blocks to appium.js thread so that if the source and screenshot fails it still continues but just reports the sourceError and screenshotError to the running browser window
* Added sourceError and screenshotError to the store
* If sourceError or screenshotError is present, show an error message in place of where source and screenshot go
> Catch source/screenshot exceptions and report error to UI

- app/renderer/components/Inspector/Inspector.js
this was kind of annoying; i noticed that when i had the new session window already open large, the inspector would be resized small. fix that.
> only resize inspector if it was previously too small

- package.json
- test/e2e/inspector-e2e.test.js
- test/e2e/main-e2e.test.js
* Transpiles mocha e2e tests using babel
* Refactor tests in main-e2e.test.js to use async/await, const, etc...
* Stubbed in inspector-e2e.test.js (later PR will have full tests)
* Doesn't restart the app after every test suite any more (was too slow)
> Refactor mocha tests to use es6

- CONTRIBUTING.md
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/SelectedElement.js
- app/renderer/components/Inspector/Source.js
- app/renderer/components/ServerMonitor/ServerMonitor.js
- app/renderer/components/Session/NewSessionForm.js
- app/renderer/components/Session/Session.js
- app/renderer/components/StartServer/StartButton.js
- package.json
- test/e2e/inspector-e2e.test.js
- test/e2e/main-e2e.test.js
- test/e2e/pages/base-page-object.js
- test/e2e/pages/inspector-page-object.js
- test/e2e/pages/main-page-object.js
(review https://github.com/appium/appium-desktop/pull/234 first; this PR is ahead of it's tip)
* Starts a fakedriver session in inspector e2e test to be used to mock Appium sessions
* Added 'package-e2e-test' script that needs to be run before running e2e tests
* Added id attributes to elements to make them easier to select
* Tests record, refresh, select & tap element
* Updated main-e2e-test.js; sometimes the updater window shows up and that messes up the tests. Now it gets the initial window count now and then tests window count relative to initial count
* Updated CONTRIBUTING to explain how to run tests
> Added inspector tests

- app/main/appium-method-handler.js
- app/main/appium.js
- app/renderer/actions/Inspector.js
- app/renderer/actions/Session.js
- app/renderer/actions/shared.js
- app/renderer/components/Inspector/Actions.js
- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/lib/client-frameworks/framework.js
- app/renderer/lib/client-frameworks/java.js
- app/renderer/lib/client-frameworks/js-wd.js
- app/renderer/lib/client-frameworks/js-wdio.js
- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/ruby.js
- app/renderer/reducers/Inspector.js
* Currently can only select items on a screenshot
* Now can either select, swipe or tap
* Tap does a tap touchaction on a absolute coordinates
* Swipe lets you select one coordinate, select a second coordinate and then it does a touch action like press -> moveTo -> release
* Shows the first coordinate as an SVG circle
* When both coordinates are selected, shows a rounded SVG line
* Updated recorder to handle these two actions
(https://drive.google.com/file/d/0ByQg0qBtDmn1N0hzUmZ3RXlYUXM/view?usp=sharing)
> Can swipe and tap on screenshot

- app/main/appium.js
- app/renderer/actions/ServerMonitor.js
- app/renderer/actions/StartServer.js
- app/renderer/components/ServerMonitor/ServerMonitor.css
- app/renderer/components/ServerMonitor/ServerMonitor.js
- app/renderer/reducers/ServerMonitor.js
- app/renderer/reducers/StartServer.js
- package.json
* Limit logs to 1000
* When logs get above 1000, the app slows down/crashes. Limit the number of rendered logs to 1000
* Log writing
* Main thread writes all logs to file
* Main thread sends the filepath of the logs to the browser window
* Added 'GetRawLogsButton' to server monitor component
* When button is clicked, opens the file externally
* Delete logfile when browser closed
* If logfile not present, show an alert to indicate that logs can't be accessed
> Limit logs and write logs to file that can be opened by user

- app/renderer/actions/Session.js
- app/renderer/components/Session/FormattedCaps.js
- app/renderer/components/Session/NewSessionForm.js
- app/renderer/components/Session/Session.css
- app/renderer/reducers/Session.js
* Added another mode in the JSON representation that allows user to input JSON string
* Shows a textarea with buttons to cancel or save
* Shows errors if the JSON is invalid
* When click the editor button, translates the caps array to editable JSON
* When JSON is saved, translate it back to the caps array format
* Don't allow saving if an error occurs, show error message
* Disable the dcap forms when raw JSON is being edited to avoid conflicts
https://drive.google.com/a/saucelabs.com/file/d/0ByQg0qBtDmn1b3hfLUk5M0NoMm8/view?usp=sharing
> Feature: Edit the desired capabilities JSON string

- app/renderer/actions/Inspector.js
* If an element is stale, when you select an element it will try to find it and won't find it in the source
* This PR, if it encounters a stale element, automatically reloads the source 
(addresses https://github.com/appium/appium-desktop/issues/319)
p.s.: @mykola-mokhnach @imurchie I know A.D. is out of your domain, but with JLipps away I need somebody to have a look at the PR's
> Reload source when selected element is stale

- app/renderer/actions/Inspector.js
* Moved element finding logic into a debounced function so that if an element is selected shortly after another one we don't do repeated calls to findElement
> Debounce calls to selectElement

- app/renderer/actions/Inspector.js
* Don't refresh page if we couldn't find element, instead just try the next locator strategy
* If nothing is found, show a notification recommending refreshing instead of just refreshing
* The previous refreshing feature was a mistake, because if the element can never be found it will ALWAYS refresh
> Use multiple selector strategies if first one doesn't work

- app/main/appium-method-handler.js
- app/main/appium.js
- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/HighlighterRect.js
- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/reducers/Inspector.js
When the user opens the 'Search for Element' modal, and searches for elements, when they select one, highlight that element on the screenshots panel.
> Highlight elements that user searched for

- package.json
- test/e2e/main-e2e.test.js
* Looks like when using electron-builder with Node 9 and building assets to the `release/` folder, PrivateHeaders does not get transferred
* Added a test that verifies the `PrivateHeaders` folder is there so that this does not occur in the future
* Also, edited the scripts in package.json so that all of the tests are run, node modules are deleted and installed and removed a redundancy
> Make test for no PrivateHeaders problem

- package.json
- test/e2e/main-e2e.test.js
* Add check-engine to package-ci script
* Require NPM 3 and Node 6 when running `package-ci` script
* This is to prevent problems we had when using newer versions of NPM/Node
* This package isn't published to NPM and these constraints don't apply to the version of Node used in the Electron main thread, thus having strict constraints isn't a big problem
* This won't effect contributors, contributors can still use engines that are defined in `devEngines`. It's only the `package-ci` script that has the strict requirements
* Fix e2e test because it uses nested `node_modules`
* Standardize names of NPM scripts
* Fixed `npm run clean` to install `rimraf` before calling `rimraf` on `node_modules`
* Upgraded postcss to resolve peer dependency issue
> Check NPM and Node versions before packaging

- app/main/menus.js
- package.json
* Change the target from NSIS to Squirrel to allow auto updating 
* Tested it by:
* Building a temporary 1.4.1 build and publishing it temporarily
* Packaging 1.4.0 app
* Installing the 1.4.0 Application file
* Installing the update
* Fixed the 'About Appium' options
> Fix windows autoupdater

- app/main/auto-updater/index.js
- app/main/auto-updater/update-checker.js
* When it's dev, make `checkNewUpdates` a no-op and skip over the autoupdate methods
* This prevents it from attempting to do an update when it's dev
(NOTE: The patch looks more complicated then it is, it just wraps the code in an if statement)
> Fix autoupdater on dev

- app/main/appium-method-handler.js
The _.toPairs return an array of object keyed-value pairs,the variableName delete operation should be
`delete elCache[1].variableName;`.
But I think,appropriate object's property values iteration should be 
`for (const elCache of Object.values(this.elementCache))`.
> Clear the variable names failed

- app/main/appium.js
- app/main/auto-updater/index.js
- app/renderer/actions/Session.js
- app/renderer/components/Session/AdvancedServerParams.js
- app/renderer/components/Session/ServerTabCustom.js
- app/renderer/components/Session/ServerTabHeadspin.js
- app/renderer/components/Session/ServerTabSauce.js
- app/renderer/components/Session/ServerTabTestobject.js
- app/renderer/components/Session/Session.js
- app/renderer/reducers/Session.js
- package.json
* This is a checkbox that allows users to accept untrusted SSL certificates (for users behind firewall). 
* This checkbox is added to Sauce, TestObject and Headspin (let me know if you think there's a better way of doing this in the UI)
* When set, it turns off the `rejectUnauthorized` http config on `admc/wd`
(https://github.com/appium/appium-desktop/issues/390)
> Allow unauthorized SSL and Proxy

- app/main/appium-method-handler.js
- app/main/appium.js
- app/renderer/actions/Inspector.js
- app/renderer/components/Inspector/HighlighterRects.js
- app/renderer/components/Inspector/Screenshot.js
- app/renderer/reducers/Inspector.js
The root element's size doesn't always reflect the screen size and this will cause coordinates and Highlighter Rectangles to mismatch what's on screen.
> Get Screen Size using WindowSize rather than coordinates of root element

- .travis.yml
- appveyor.yml
- package.json
* Update Appium to 1.8.0
* Update Electron to 2.0.0
* Update electron-builder to 20 and get rid of outdated version hack
* Use NPM 5 on appveyor so we get a flat hierarchy
I'd like to try Travis again on Mac. Maybe the new electron-builder will work
> Prepare for 1.6.0

- CHANGELOG.md
- app/main/auto-updater/index.js
- appveyor.yml
- env/.env-nsis.js
- env/.env.js
- package.json
- webpack.config.electron.js
* Add nsis builds. Squirrel can be flakey at times and NSIS also allows per-machine builds, however it doesn't support auto-update.
* Add build environments specific to target. This is necessary for NSIS builds so that the UI doesn't show the 'Install Updates' message
* Added 1.6.1 release notes, 1.6.0 had a defect and it's basically just going to be a dead tag now.
* Added NSIS builds to AppVeyor
> Build updates

- .vscode/launch.json
- CONTRIBUTING.md
- package.json
* Added .vscode configuration so that you can debug directly in VSCode
* Added --inspect flag to `npm run dev` to make that work
* The --inspect flag also makes it possible to debug in Chrome DevTools
* Added documentation in CONTRIBUTING.md to explain how it works
* I've tested this in both and it works perfectly, it even respects source-maps so that you can debug src code instead of transpiled code
> Add debugging to dev

- .travis.yml
- app/main/auto-updater/index.js
- env/.env.js
- package.json
- webpack.config.electron.js
* Used the ENVIRONMENT_PLUGIN
* Export environment config based on plugin. Right now .nsis is the only alternative
* Also silenced webpack so we don't see the long package installation messages
* Also changed npm install to npm ci for Travis so that it gets the packages defined in `package-lock.json`
> Fix: .env properly loads based on target

- app/renderer/actions/Inspector.js
* When an element is 'selected' it tries locating that element by a strategy that's inferred from the source xml
* Previously, it was trying one and then showing 'Element Not Interactable' if the first didn't work
* Now, it tries them _all_ and then shows 'Element Not Interactable' if none of them work
> Don't set 'interactions not available' until we've tried all strategies

- app/renderer/components/Inspector/Inspector.js
- package-lock.json
- package.json
Adds support for copying the source xml to the system clipboard. 
Main use case using the search for element can be slow due to the page source being refreshed. This allows a user to copy the xml to any other xpath tester available to them. We have been using this quite a bit and find it faster to work with. The copy button is in the tooltip section of the inspector.
Lastly, if someone knows why my package.json went all crazy I'm happy to update prior to merging if this gets accepted
> Add support for copying source XML to clipboard

- app/main/main.development.js
- app/main/menus.js
- app/renderer/components/Session/Session.js
- app/shared/cloud-providers/config.js
- app/shared/cloud-providers/index.js
(Replaces an older PR)
* Add a submenu in 'View' that lets you toggle which cloud providers are visible
* Toggling the submenu items changes the state using `electron-settings` so that the user preferences are persisted across sessions
* Created a `shared` folder that has the logic for cloud providers, eventually I'd like to move all of the cloud provider logic there so that there's only one place where we configure it
(cc: @llaskin)
> Add cloud provider visibility menu

- app/main/appium.js
- app/main/helpers.js
- app/main/menus.js
- app/renderer/actions/Config.js
- app/renderer/actions/Stub.js
- app/renderer/components/Config/Config.css
- app/renderer/components/Config/Config.js
- app/renderer/components/StartServer/StartButton.css
- app/renderer/components/StartServer/StartButton.js
- app/renderer/components/StartServer/StartServer.js
- app/renderer/components/Stub.js
- app/renderer/containers/ConfigPage.js
- app/renderer/reducers/Config.js
- app/renderer/reducers/Stub.js
- app/renderer/reducers/index.js
- app/renderer/routes.js
* Added a 'Config' window that is either opened from menu or from the start server page
* Added form that sets environment variables JAVA_HOME and ANDROID_HOME
* Shows defaults as whatever 'appium-desktop' finds inside of `process.env` originally
* When these are saved, saves it to appium-settings
* When app is loaded for first time, `process.env` is extended with these saved env vars
* When config is 'Saved' the user is asked to 'Restart Now' for changes to take effect
* Other
* Added 'Stubs' for actions, reducers and components for cutting-and-pasting purposes later on
* Moved browser window opener to a helper method
* This is how it looks, we'll probably want to change it to something more subtle
> ANDROID_HOME set from in UI

- app/renderer/components/Session/ServerTabBrowserstack.js
While working on https://github.com/appium/appium-desktop/pull/594 , I noticed that the Browserstack tab has a couple of typos.
The typos in the env vars would currently cause the UI not to show that the env vars are detected.
This PR should fix it and help the people using Browserstack :)
> Fix two typos in Browserstack tab; fixes env var usage

- app/renderer/components/Inspector/shared.js
You.i Engine now supports React Native and we've added support for it's testID to be used in Appium.
https://facebook.github.io/react-native/docs/view#testid
`rntestid` was added to the selector mapping and uses `id` as it's search strategy.
> Added React Native testID to Strategy Mappings

- app/main/appium.js
- app/renderer/reducers/StartServer.js
- package-lock.json
- package.json
- test/integration/update-checker.integration-test.js
* This [issue](https://github.com/appium/appium/issues/11320) causes Appium Desktop to break when it tries calling 'getParser'
* Temporary workaround is to just comment out the code that calls 'getParser' because it doesn't actually get used
* I could remove it completely, but I wanted to check first to see if it's there for a reason
> Remove getParser code

- app/renderer/actions/Session.js
The default values (`hostname`: `127.0.0.1` and `port`: `4723` described in the placeholders) are not applied which throws a `Could not start session`.
> default custom server port to 4723 which is the value in placeholder

- app/renderer/lib/client-frameworks/js-wdio.js
* In the chainify, don't accept _any_ character after `el`.... only accept integers
* Previous implementation, it was looking ahead to the last instance of `.` and if you had an email in a string it would clip it up until the `. in `email@email.com`
> Make lookahead for "." lazy

- app/renderer/components/ServerMonitor/ServerMonitor.js
- app/renderer/components/StartServer/DeletePresetButton.js
- app/renderer/components/StartServer/SavePresetButton.js
- app/renderer/components/StartServer/StartButton.js
- app/renderer/components/StartServer/StartServer.js
- app/renderer/components/StartServer/shared.js
- app/renderer/containers/App.js
- package-lock.json
- package.json
First step before upgrading to React 16 is to use 3rd party PropTypes (internal PropTypes are deprecated in 16)
> Use 3rd party prop types for React

- .travis.yml
- appveyor.yml
- package.json
E2E tests inexplicably stopped working on Azure Pipelines (I even attempted re-running old, formerly passing builds, with no problems)
Stopping running E2E tests on Azure until it gets sorted out.
> Don't run E2E tests on Mac (for now)

- package.json
Since it's not used anyway, we just not need to include the extra packages
> Get rid of the obsolete squirrel stuff

- app/renderer/components/Session/CapabilityControl.js
- app/renderer/components/Session/NewSessionForm.js
**Bug**: filePath dialogs were getting `this.getLocalFilePath() is undefined` errors.
**Fix**: Moved getLocalFilePath declaration to CapabilityControl.js
> Fix filePath dialogs

- package.json
Tried doing this at a level above the platforms, but `${platform}` comes back as 'darwin' for all platforms since it isn't in the platform specific block at the time the substitution is made.
> Building with platform in output package filenames

- app/main/menus.js
- assets/locales/en/translation.json
Make it easier for people to find the place where they can add/improve Appium Desktop translations
> Add a separate menu item for translations stuff

- app/main/appium.js
- package-lock.json
- package.json
Greenkeeper upgrade to Babel@7.4 broke the build due to a defect in ES6 (incorrect `export` syntax)
This PR fixes that and also bumps up the minimum to 7.4.0
> Bump up minimum babel monorepo

- package-lock.json
- package.json
Drops `pre-commit` use Husky because it supports `pre-commit` _and_ `pre-push`
`pre-commit`: Just run lint
`pre-push`: Run lint, unit and integration tests
> Use husky to do pre-commit and pre-push hooks

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/Inspector.js
- app/renderer/components/Inspector/RecordedActions.js
The last commit to add the `Actions` tab messed up the CSS. This fixes it all.
> fix: inspector CSS

- app/main/appium-method-handler.js
Right now sessions prompt users after 30 minutes to keep sessions alive and they're only given 5 minutes to respond to the prompt.
This doesn't work well for people who are multitasking between running an Appium session and doing other work.
This PR bumps up the number to 24 hours with 1 hour to respond to the prompt. 
I think we can trust Appium users to use their cloud concurrency responsibly.
> Bump up no activity limit to 24 hours

- app/renderer/components/Inspector/Actions.js
Need to parse 'settings' JSON before passing it through to wd
(cc: @wswebcreation)
> fix: Parse JSON for updateSettings

- app/main/appium-method-handler.js
* The current way of getting source, screenshot and windowSize is calling each one-after-the-other
* This PR makes it so that they all get called at once and then the promise resolve once we have a result for all three (whether it's successful or an error). Should give a pretty noticeable performance bump.
* Pardon the Promises abomination. `Promise.all` doesn't support waiting for all promises to resolve. I needed a solution that completes all three of the promises and then sends the result back.
* Also note, I wanted to use `finally` to call `checkShouldResolve`, but there's a race condition that causes `finally` to sometimes be called before `then` or `catch`.
> Get source, screenshot and windowSize concurrently

- app/main/appium.js
- app/renderer/actions/shared.js
- package-lock.json
The 'ignoreResult' flag was causing the result to not be sent back to the renderer process. This was done because there's some cases where we don't want the result to be displayed using "notification" but this is a problem for highlighting an element because it wasn't getting the result.
This changes it so that 'ignoreResult' still sends the result back to the renderer but skips the notification if it's 'ignoreResult=true'.
> fix: Stop ignoring result for element location/size

- .gitignore
- app/renderer/actions/Session.js
- app/renderer/components/Session/Session.js
also, fix minor bug where user could have cloud provider saved as server type,
but then it is removed from the visible providers list. default to remote in
that case.
> make sure to save server type change even without setting change

- app/renderer/components/Inspector/Inspector.js
this has also been bugging me. with this change there's no more horizontal or vertical space gap to the right or below the screenshot image.
> intelligently resize screenshot and source tree widths

- app/main/appium.js
- app/renderer/actions/Session.js
Currently, `getRunningSessions` sends requests to `/wd/hub`.
Custom server tab and other services also can configure their own path instead of `/wd/hub`.
But then, this feature never listens to the paths.
In this PR, I changed to pass `path` and `ssl` preference to the request.
(And I understood `session.server.${serverType}.hostname` etc are used then..)
Can you review this? I wondered if this implementation had intentions.
@jlipps @dpgraham
> make configurable get running sessions path

- app/renderer/actions/Session.js
https://github.com/appium/appium-desktop/pull/979 for other providers.
AppiumDesktop has a feature which gets current running sessions by Appium Server via `getSessions` command like below image. (POST to `https://host:port/wd/hub/sessions`) Before https://github.com/appium/appium-desktop/pull/979 , it worked partially.
Make it work correctly, below values are necessary.
I've added them as this PR.
```
session.server.${providername}.host
session.server.${providername}.port
session.server.${providername}.path
session.server.${providername}.ssl # true or false
```
I assume some of providers won't work `getSessions` command on your environment.
Then, you can ignore the feature like adding your name like below.
https://github.com/appium/appium-desktop/blob/44c7f49ce482e25fca3c86f6a353bed1963f2 …
> apply session.server.${providername}.host/port/path/ssl

- package-lock.json
- package.json
When I tried `npm run dev`, I faced following error:
```
[0] App threw an error during load
[0] TypeError: Cannot set property 'default' of undefined
[0]     at Object.<anonymous> (/Users/rhysd/Develop/github.com/appium/appium-desktop/node_modules/i18next/index.js:5:24)
[0]     at Object.<anonymous> (/Users/rhysd/Develop/github.com/appium/appium-desktop/node_modules/i18next/index.js:7:3)
[0]     at Module._compile (internal/modules/cjs/loader.js:711:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
[0]     at Module.load (internal/modules/cjs/loader.js:620:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
[0]     at Module.require …
```
> Fix build by updating i18next to 17.0.3

- ci-jobs/package.yml
- ci-jobs/weekly.yml
The weekly pipeline that updates the crowdin translations and the package-lock.json has been routinely approved and merged for months now. I think it's safe to just push directly to master and skip the pull requests.
> Push Crowdin changes directly to master

- app/main/appium.js
If the capability `deviceName` is not defined (for example if it is defined by appium server's default capabilities), this PR will prevent  `wd` from injecting `"browserName": "firefox"`.
See https://github.com/admc/wd/blob/13ffe77a1a599dcff5dcb8242c003e14cfcab57d/lib/webdriver.js#L83-L91
Fixes #667
> fix: Prevent wd from injecting default desired capabilities

- app/renderer/components/StartServer/AdvancedTab.js
- assets/locales/de/translation.json
- assets/locales/en/translation.json
- assets/locales/es-ES/translation.json
- assets/locales/fa/translation.json
- assets/locales/fr/translation.json
- assets/locales/hi/translation.json
- assets/locales/it/translation.json
- assets/locales/ja/translation.json
- assets/locales/kn/translation.json
- assets/locales/ko/translation.json
- assets/locales/ml-IN/translation.json
- assets/locales/pa-IN/translation.json
- assets/locales/pt-BR/translation.json
- assets/locales/pt-PT/translation.json
- assets/locales/ru/translation.json
- assets/locales/te/translation.json
- assets/locales/zh-CN/translation.json
- assets/locales/zh-TW/translation.json
Previously wrongly spelt as supressed
Fixes #1060
> fix: Update spelling of suppressed

- app/renderer/actions/Session.js
Hi,
We've made sure that `getRunningSessions` will work, please remove testingbot from the avoidServerTypes.
Thanks
> feat: Remove testingbot from avoidServerTypes in getRunningSessions

- ci-jobs/templates/package.yml
Not sure this need on CI, too, but I got 'command not found: build' error when I ran 'npx build --publish never'  in another package. Then, I also tried this repository and got the same error.
If 'npx build' does work on CI, this PR will need, I assume.
> chore: add electron-builder to avoid no build command error

- app/renderer/components/Inspector/ElementLocator.js
- app/renderer/lib/client-frameworks/java.js
- app/renderer/lib/client-frameworks/js-wd.js
- app/renderer/lib/client-frameworks/js-wdio.js
- app/renderer/lib/client-frameworks/python.js
- app/renderer/lib/client-frameworks/robot.js
- app/renderer/lib/client-frameworks/ruby.js
- Add Android viewtag (Espresso Only) as search locator strategy 
Edit: just found out how u guys implement script recording, currently, it will crash if we use viewtag for script recording
i'll take a look at supported library and how they use viewtag as locator strategy
_TODO:_
> [WIP] feat: add viewtag as search locator strategy

- ci-jobs/templates/package.yml
- package-lock.json
- package.json
I guess https://github.com/appium/appium-desktop/pull/1047/files is the cause about the failing tasks.
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=5650
```
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.155.1/work/_temp/7b90ec96-5cc2-4f6b-9763-b5a07a5adf28.sh
• electron-builder  version=21.2.0 os=18.7.0
• loaded configuration  file=package.json ("build" field)
• packaging       platform=darwin arch=x64 electron=5.0.6 appOutDir=release/mac
• asar using is disabled — it is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
⨯ /Users/vsts/agent/2.155.1/work/1/s/$(CSC_LINK) doesn't exist
```
Then, maybe https://github.com/appium/appium-desktop/pull/1079 also should be reverted.
---- …
> fix: Revert electron-builder in order to complete publishing package tasks

- app/main/auto-updater/update-checker.js
`res` gets value if the latest release tagged version on github is not the current local app version.
Thus, update dialog appears when a user has a newer pre-released version than the latest release tagged version on github.
e.g.
A user has 1.15.0 on their local, but this repository's release tagged version is 1.14.0
=> Then, the local version shows update dialog to 1.14.0
We can see questions about this issue on this repository. So, I've added version comparison after getting the `res`. So, if the local version is greater than the github one, no available device dialog appears.
> fix: shows newer version available dialog only when the local version is lower than it

- app/main/menus.js
closes https://github.com/appium/appium-desktop/issues/1037
I found a redundant bracket. It fixes the issue. I checked on windows env.
> fix: menu items for non-mac

- app/renderer/components/Session/SavedSessions.js
- before: We cannot get items in a hidden area. The below image had 11 items, but we can select 3 of 11. They appear after resizing the size of the window.
- after:
We should calculate the available area dynamically
> fix: add scroll in saved capability sets

- app/renderer/components/Inspector/Inspector.css
- app/renderer/components/Inspector/SelectedElement.js
- before
- after
----
closes https://github.com/appium/appium-desktop/issues/957 
This trick was linked in https://ant.design/components/table/
> fix: break word in selected element

- app/main/appium-method-handler.js
Starting from version 1.12.1, PR #916 caused Perfecto and other cloud providers an issue when trying to open a device in the Appium desktop. The screenshot keeps spinning and the source keeps loading. This is because the commands are no longer being processed concurrently rather now they are being processed asynchronously. We are requesting that you perform a revert for this change.
> revert: Revert "Get source, screenshot and windowSize concurrently"

- app/renderer/components/Config/Config.js
- app/renderer/components/ServerMonitor/ServerMonitor.js
- app/renderer/components/Session/CloudProviderSelector.js
- app/renderer/components/Session/Session.js
- app/renderer/components/StartServer/PresetsTab.js
- package-lock.json
- package.json
Update electron version to v6.
v7 is available, but let me update the version one by one.
- `componentWillMount` was changed.
- Move the logic which has fetching data into `didMount`
```
/Users/kazu/GitHub/appium-desktop/node_modules/react-dom/cjs/react-dom.development.js:11494 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project …
```
> feat: update electron version to v6

- app/renderer/components/Inspector/shared.js
appium models contain KV pairs, where the values of those pairs may contain double quote characters: `"`.
isUnique wraps a query in double quotes, thus the xpath.select(...) call cannot parse the passed query due to bad quote inputs.
- escape double quotes from the query
partially fixes #1057.
> fix(shared): escape double quotes within a double quoted template query

- app/renderer/components/ErrorBoundary/ErrorBoundary.css
- app/renderer/components/ErrorBoundary/ErrorBoundary.js
- app/renderer/index.js
- ci-jobs/package.yml
- ci-jobs/pr-validation.yml
#1057 and other related issues suffer `Error`s being thrown, yielding an unactionable, blank screen.
improve the UX by adding an error boundary, communicating the exception to the user, and inviting her to create a new github issue.
> feat: add <ErrorBoundary /> for improved error condition UX

- package-lock.json
- package.json
After #1161 , `xmldom` has been removed from `dependencies` while we need the module in dependencies.
It exists in devDependencies so when we run `npm run dev`, it works without errors. But once we build it as a release module, the app raises no `xmldom` module error when the app launches
In this PR, I've moved the module to `dependencies`. I also update `package-lock.json`.
I confirmed this change make the release build succeed and launch it.
> fix: no xmldom module error in release build

- app/renderer/components/Inspector/shared.js
Added some commands for web/context
`methodName` were in https://github.com/admc/wd/blob/67dae3823e8a457c10d9fbe81578684bbb9938d9/doc/api.md
Command tree and their name were http://appium.io/docs/en/commands
I've tested they worked on my local
> feat: Add context and some web commands as actions

- app/renderer/components/Session/SavedSessions.js
Saved session item in saved capabilities tab does not work because the `this.onRowClick` property is `undefined`. As far as checking the implementation, it looks a typo of `this.onRow`. This PR fixes it.
> Fix click does not work on saved session item in saved capabilities tab

- app/renderer/actions/Session.js
Sometimes the cloud port is not sent correctly from the UI, therefor setting it to the default in Session.js when it is undefined.
> fix: set Perfecto cloud provider default port when undefined

- app/renderer/components/Inspector/Source.js
I noticed following warning appeared in DevTools console:
It seems that `treeData` property should be used to set tree nodes data.
https://ant.design/components/tree/
This PR fixes the point. After applying this patch, I confirmed the warning no longer occurred and tree view worked fine by connecting to sample Android app as follows:
> fix: Use treeData prop for Tree component instead of deprecated children prop

- app/renderer/components/Session/SavedSessions.js
I noticed saved session was not clickable. In table of 'Saved Sessions', `onClick` is used for handling click events. However, as far as I checked it seemed mistake. There is no `onClick` property.
https://ant.design/components/table/#Table
Instead, `onRow` property is available.
https://ant.design/components/table/#onRow-usage
After applying this PR, I confirmed click got effective.
> Fix 'Saved Session' table is not clickable

- app/renderer/components/Inspector/Inspector.css
Fixes two items:
1. Vertical scroll in source container https://github.com/appium/appium-desktop/issues/1316
2. Max height in the inspector container
- Before this change, the container had `48px` redundant bottom area
> fix inspector container style

- app/renderer/components/AntdType.js
- app/renderer/components/Inspector/RecordedActions.js
- app/renderer/components/StartServer/DeletePresetButton.js
- app/renderer/components/StartServer/SavePresetButton.js
- app/renderer/components/StartServer/StartServer.js
Fixes warnings about `type`. Their default should be `default`. `default` is used in some places, but not rest of them are still `null` or `''` (blank)
https://ant.design/components/button/
They seem okay, but let me check them again later
> fix: warnings for type

- app/renderer/components/Inspector/Actions.js
This change fixes two warnings in Actions.
- React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. antd select
- a unique key
> fix: warnings in Actions

- .dependabot/config.yml
dependabot/config.yml does not support format like ignoring only `patch`, but we want to reduce PR frequency.
Let me change the update schedule to weekly for now
> chore: update bot cycle weekly

- package-lock.json
- package.json
like https://github.com/appium/appium-desktop/commit/c5e8190075c16591174844d59076830214206270 (1.15.0-1).
This is necessary before https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=9936&view=logs&j=52ae2be2-cccc-589a-915f-9637704a0c53&t=20f9c7c9-e480-56d1-56b3-bbd543d49b14 ...
> chore: bump version to run ci

- app/renderer/components/Inspector/Source.js
fix https://github.com/appium/appium-desktop/issues/1449
`elemObj.children` could be undefined.
> fix: no children in source

- package-lock.json
- package.json
to push current master
- Bump the version of AD
- Bump Appium version to 1.18.0 beta (by `npm install --save appium@1.18.0-beta.0`)
After this, let me push a new module as beta
> chore: Bump beta 1.18.0

- app/main/appium-method-handler.js
- app/renderer/components/Inspector/HighlighterRects.js
https://github.com/appium/appium-desktop/pull/1438 introduced context-related commands, but some platform does not support them like Windows and macOS (https://github.com/appium/appium-desktop/issues/1449#issuecomment-655966896) .
We should keep the previous way for such platforms.
In this PR, AD will follow the previous logic if the app under test does not have get contexts command.
I also fixed some errors I found in tests.
> fix: keep compatibility in _getContextsSourceAndScreenshot for platforms which have no context commands

- app/renderer/actions/Session.js
This PR fixes the missing PR for the Appium 1.8.0 Android driver to set `ensureWebviewsHavePages:true` by default. I also restructured the code a bit
> fix: add temporary fix for android hybrid apps and restructure code

- app/renderer/actions/Session.js
AD currently shows below message as the result of findElements via an icon when the given parameter is an invalid selector.
For example, my below screenshot is for macOS, but I sent a selector for Android.
```
Call to '10' failed
[elements("-android datamatcher","asd")] Response value field is not an Array.
```
I could not find `findElement` request via icon and actions. So, I only tweaked this case since I could not replicate an error case for `findElement`.
This change does not affect a case which it returns `[]`.
---
closes https://github.com/appium/appium-desktop/issues/1470
> fix: print the original error response if given error message has the original error for findElements

- .github/workflows/weekly.js.yml
Let me merge this later to check the behaviour...
Instead of https://github.com/appium/appium-desktop/blob/master/ci-jobs/weekly.yml
We do not deed to consider token stuff to handle GitHub repositories on GitHub Actions.
> ci: Create weekly.js.yml

- package-lock.json
- package.json
> chore: bump AD version to 1.18.0

- app/renderer/actions/Session.js
Closes https://github.com/appium/appium-desktop/issues/1505
Attach to an existing session is `newSession(null, attachSessId)`. Then, `addCustomCaps(null)` raises an error in `const {browserName = '', platformName = ''} = caps;`. `{}` works both cases.
> fix: attach to an existing session

- package-lock.json
- package.json
Current 1.18.0 has an issue to attach to an existing session. (The feature is not available at all)
https://github.com/appium/appium-desktop/issues/1505
> chore: bump to 1.18.0-1 as a hotfix

- app/renderer/components/Session/CapabilityControl.js
closes https://github.com/appium/appium-desktop/issues/1492
Not sure since when, but `showOpenDialog` should be `then` syntax.
`this.handleSetType` is always `null`, so cannot bind.
After:
https://github.com/electron/electron/blob/v6.0.0/docs/api/dialog.md#dialogshowopendialogbrowserwindow-options
> fix: get filePaths

- app/renderer/actions/Session.js
- app/renderer/components/Session/ServerTabSauce.js
- app/renderer/components/Session/Session.css
- assets/locales/en/translation.json
This PR will:
- add the new Sauce Labs Unified Platform US endpoint as the default
- fixes the layout to a normal row
- Adds a tooltip with information on how to use the old endpoint
> feat: add Sauce Labs Unified Platform endpoint for US

- app/renderer/actions/Inspector.js
- app/renderer/actions/Session.js
- app/renderer/components/Inspector/shared.js
- app/renderer/lib/appium-client.js
fixes https://github.com/appium/appium-desktop/issues/1596
We missed to clean current client instance in quit the session, so the instance remains in next one.
Then, the next session send requests as the previous session_id. Then, it gets invalid session error.
---
I also added W3C command since we know can follow W3C spec as primary method
> fix: send wrong session id

- app/renderer/actions/Session.js
Now AD sends W3C spec capabilities. Capabilities should follow the spec.
Vendor prefix will be removed for OSS, `desiredCapabilities`, in a new session request automatically.
> fix: add appium prefix for w3c in prefix capabilities

- shared/menus.js
This item will be at the bottom of the below list.
> add: a link to translation project in help for non-macOS env

- app/main/appium.js
- app/renderer/actions/Session.js
1. The "Attach to session" tab of the inspector app doesn't return the running sessions for BrowserStack, this happens because the BrowserStack APIs require the user credentials otherwise it returns a response code of 401.
2. This PR adds the Authorization header for the `/wd/hub/sessions` requests i.e. for `getCurrentSessions`
3. Also add the ability to use the `BROWSERSTACK_PORT` set in the environment variables for defining the port and setting SSL to true if the port is 443.
> fix: getCurrentSessions for cloud providers using Basic Auth

- inspector/app/renderer/actions/Session.js
1. The "Attach to session" tab of the inspector window doesn't list the running sessions for BrowserStack, this happens because the BrowserStack APIs require the user credentials otherwise it returns a response code of 401.
2. This PR adds the `Authorization` header for the `/wd/hub/sessions` requests.
> fix: getRunningSessions for BrowserStack & other cloud providers that use basicAuth

- app/main/appium.js
1. Attached sessions were getting timeout due to inactivity as we were not displaying the "Session Inactive" prompt to the user in case of an attached session.
2. This PR fixes the above issue and we start the `runKeepAliveLoop` similar to what we were doing for a regular session [here](https://github.com/appium/appium-desktop/blob/1.20/app/main/appium.js#L223-L225).
> fix: attached sessions getting timeout due to inactivity

- app/renderer/components/Session/AttachToSession.js
- app/renderer/reducers/Session.js
1. Attach to session placeholder text `enterYourSessionId` was not getting displayed as we were setting the value to `''` in case there are no running sessions, however, the `antd` expects this value to be `undefined` instead. For reference check [this](https://stackoverflow.com/a/45558497) stackoverflow link.
2. Whenever the `GET_SESSIONS_DONE` event is received for the first time we set the `attachSessId` inside the `state` variable, however, for the subsequent occurrences of this event we never update the `state.attachSessId` as we had already set that once initially. This leads to stale sessions that are not running anymore and still getting listed. This stale entry is only removed if the user selects a valid entry from the dropdown so that the `SET_ATTACH_SESS_ID` event is triggered …
> fix: stale session ids being displayed in the attach to session dropdown

- app/renderer/components/Session/AttachToSession.js
Once #1693 is merged users will be able to view the list of running sessions in the attach to session window. It is difficult to filter the sessions via the session-id, therefore, adding the `sessionName` (if present) to the list of `importantCaps`.
**Screenshot from the dev build**
<kbd>![sessionName in attach to session list](https://user-images.githubusercontent.com/10832531/107780683-03f23580-6d6d-11eb-930f-b8ebb3486666.png)</kbd>
> feat: add sessionName in the attach to session dropdown

- app/renderer/actions/Session.js
1. If Appium desktop is installed and we add a cloud provider then the "Attach to session" tab doesn't list any running sessions. This happens because the request to the remote server is never sent as the host, port & the path for the selected server type is not yet defined in the `session` variable. These values are populated only once we trigger a new session via AD for the newly added cloud provider, as it was only being set in the `NEW_SESSION_REQUESTED` event.
2. To fix the above issue I have created a method `getServerInfo` that returns the server information for the currently selected server type. This method either returns the values from the session variable or returns the default value.
3. The method `getServerInfo` is also used for both the `NEW_SESSION_REQUESTED` and …
> fix: request to remote server not sent in case of fresh installation

- app/main/appium-method-handler.js
- app/renderer/actions/Session.js
When switched to the webview of a hybrid app the elements on the screenshot were not aligned with the expected position.  See screenshot
**Android:**
**iOS:**
This PR will fix that by determining the position of the first webview on in the hybrid app, see below
**Android:**
**iOS:**
This will also fix the issue that Android hybrid apps got stuck when switching to the webview. The `nativeWebScreenshot` was needed to get a full screen screenshot instead of the ChromeDriver Webview screenshot
> fix hybrid element position determination

- ci-jobs/templates/package.yml
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=20481&view=logs&j=f87c6499-3401-572f-ac24-cec18d4bfbce&t=4032fcf8-7e70-54e0-2d0a-53cd538a71f4 failed in Win build as code signature has been expired.
I don't know where sets the signature. Probably the below section in the Azure??? I don't know the exact value neighter.
In my local Win app (Win 10 env though) worked without the sign. So, a module by `npx electron-builder build -w --ia32 --x64` worked.
So, I wonder we can remove `CSC_LINK` for this purpose since we won't publish these apps to their online store. Or we probably can ask JSFoundation...? @jlipps 
https://github.com/appium/appium-desktop/releases/tag/v1.22.3 's Win modules are built by `npx electron-builder build -w --ia32 --x64 --publish never` on my local …
> chore: comment out CSC
